version: '3'
services:
  mongodb-replicate-app1:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app  
    networks:
      - my-mongo-cluster
    command: nodemon -L index.js
networks: # magic
  my-mongo-cluster: 
    external: true  # magic or it not connect    